backend:
  name: github
  repo: nourhen11/eshop

media_folder: static/uploads
public_folder: uploads

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'PublishDate', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'produt'
    label: 'product'
    format: 'json'
    folder: 'assets/content/product'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'string' }
      - { label: 'Size', name: 'size', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Category',name: 'category', widget: 'select', options: ["BAGUES", "BOUCLES A OREILLES", "BRACELETS","c","BOX SET"]}
            