backend:
  name: github
  repo: nourhen11/eshop

media_folder: static/uploads
public_folder: uploads

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    identifier_field: title
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'PublishDate', name: 'date', widget: 'datetime',dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm"  }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'produt'
    label: 'product'
    format: 'json'
    folder: 'assets/content/product'
    create: true
    identifier_field: title
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - {label: "Publish Date", name: "date", widget: "date",format: 'MMM Do YY'}
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'metal', name: 'color',widget: 'select', options: ["OR BLANC", "OR JAUNE", "OR ROSE","PLATINE"] }
      - { label: 'Size', name: 'size', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Quantity', name: 'quantity', widget: 'number' }
      - { label: 'Category',name: 'category', widget: 'select', options: ["BAGUES", "BOUCLES A OREILLES", "BRACELETS","COLLIERS ET PENDENTIFS"]}
            